# Chapters — UI Design System

Companion to `2026-07-17-hosted-ui-structure-design.md`, which specs page
structure and flows but explicitly deferred visual design tokens/theming
to "UI-phase start." This is that pass. Produced via `/design-consultation`
(gstack): competitive research (Linear, Obsidian, Craft), an independent
subagent design proposal (tagged `[single-model]` — Codex CLI wasn't
available locally), synthesis, an HTML preview verified by screenshot in
both themes, and an anti-slop audit (`impeccable`) that caught and fixed
two overused-font findings before this was written down.

**Memorable-thing brief** (owner's own words): "robust, easy to use and
navigate, and easy to setup." Every choice below answers that.

## Aesthetic direction

**Editorial/Refined — "paper & ink," not "dark IDE glass."** Chapters'
actual pitch is *plain files on disk, yours forever*. Paper is the
material metaphor for permanence; a glowing dark screen is the metaphor
for ephemeral app state. So the product is **light-first**: dark mode
exists as a genuine secondary "night mode," never the brand's face —
a deliberate reversal of the Linear/Obsidian/Vercel dark-first convention
common to this whole category.

Decoration level: minimal, with one intentional touch — a faint paper-grain
texture on the canvas (costs nothing in performance, reinforces the
material metaphor).

**Anti-reference:** Craft's soft pastel/illustrated consumer style — too
soft for "robust."

## Typography

| Role | Font | Why |
|---|---|---|
| Display / Headings | **Petrona** | Serif with real character — "written by someone," not generated by a template. (Originally proposed Fraunces; swapped after `impeccable` flagged it as an overused AI-generated-UI default.) |
| Body / UI | **Hanken Grotesk** | Warm geometric-humanist, legible at small sizes for hours at a time without going cold. (Originally proposed Plus Jakarta Sans — same reason for the swap.) |
| Code / file paths / frontmatter / timestamps | **IBM Plex Mono** | Signals engineering rigor; itself an openly-licensed typeface, fitting for a self-hosted OSS product. |

All three load via Google Fonts (`fonts.googleapis.com`) for now; self-hosting
the font files is a reasonable later hardening pass for fully offline
self-hosted instances, not a blocker.

Scale: display 34–64px / body 15–16px / UI 13–14px / eyebrow labels 11px,
tracked uppercase, 0.12em letter-spacing.

## Color

Restrained, but **functionally dual-accent** — color is rare, and when it
appears it means something specific: **who touched this**, not decoration.
This is the single most useful thing color can do for a product whose core
differentiator is permission-scoped AI access.

| Token | Light | Dark | Meaning |
|---|---|---|---|
| Canvas | `#F4F1EA` | `#17140F` | page background |
| Surface | `#FAF7F0` | `#201C15` | raised: editor, modals, cards |
| Recessed chrome | `#EAE5D8` | `#0F0D0A` | sidebar, rails, toolbar |
| Primary text (ink) | `#1C1A16` | `#EDE8DD` | |
| Muted text | `#6B6558` | `#A39C8C` | |
| **Human accent** | `#BA3B1D` | `#E2683F` | anything a person authored: links, cursor, primary buttons |
| **AI/machine accent** | `#2B6E6B` | `#4FA39F` | AI-suggested edits, MCP-written content, inferred graph edges, the AI's own live collab cursor |
| Success | `#3D7A4F` | `#6FBF83` | semantic |
| Warning | `#B8862E` | `#D9A94D` | semantic |
| Error | `#BA3B1D` | `#E2683F` | shares the human-accent hue deliberately — both mean "attention, look here" |
| Info | `#2B6E6B` | `#4FA39F` | shares the AI-accent hue |

Both human and AI accents check clean at WCAG AA on the canvas (vermillion
≈ 4.99:1, teal ≈ 5.25:1).

**Collaborator cursor palette ("inks")** — hashed deterministically per
user, same approach Figma uses (`color-hash` on username), but curated to
five hues rather than an arbitrary rainbow, and **teal is never assigned to
a human** — it's reserved exclusively for the AI/MCP's own live cursor when
actively editing through the collaboration engine (extends the existing
"AI visibility" flow in the hosted-UI spec — the labeled AI presence was
already speced, teal cursor is its natural expression, not a new mechanic).

- Vermillion `#BA3B1D` (red ink)
- Indigo `#3B4C8C` (blue ink)
- Plum `#7A3B6B` (violet ink)
- Ochre `#8C6D1F` (gold ink)
- Forest `#3B6B4C` (green ink)

## Spacing

Base unit 8px, comfortable density (not cramped — "easy to navigate").
Scale: 2xs(2) xs(4) sm(8) md(16) lg(24) xl(32) 2xl(48) 3xl(64).

## Layout

Grid-disciplined. Chrome stays at the edges, content owns the center —
already locked in `2026-07-17-hosted-ui-structure-design.md`. Border
radius: sm 4px / md 8px / lg 12px / full 9999px. Max content width ~1180px
for chrome pages; the Editor's sidebar (220px) and rail (260px) are
fixed-width, center panel fluid.

## Motion

Intentional, not expressive. GSAP + anime.js are reserved for transitions
that aid comprehension (rail slide, ⌘K palette open/close, the autosave
whisper in the breadcrumb bar) — never decoration for its own sake.
Easing: enter `ease-out`, exit `ease-in`, move `ease-in-out`. Duration:
micro 50–100ms, short 150–250ms, medium 250–400ms, long 400–700ms.

## Signature interactions

Two mechanics that answer "think outside the box, the way Yildizim was" —
each translates something Yildizim already does into this edition's own
material instead of copying it watered-down:

- **Ink-fade decay.** In the flat 2D graph view (this edition's Home,
  per the open-core boundary), notes untouched for a long time visually
  fade — lower ink opacity, slight desaturation — so staleness is
  something you see at a glance in the graph, not something you look up
  in metadata. Mirrors Yildizim's star-decay-to-Main-Sequence mechanic,
  expressed as fading ink rather than a dying star.
- **Collaboration cursors.** Figma's pattern (colored pointer + username
  tag beneath it), grounded in the real implementation rather than
  assumed: `y-codemirror.next`'s `yCollab` awareness protocol natively
  handles cursor position + user color + user name (`awareness.
  setLocalStateField('user', { color, name })`) — no custom WebSocket
  cursor-tracking needs to be hand-rolled. The cursor shape tapers toward
  a pen-nib rather than Figma's generic arrow, so it reads as this
  product's own rather than a literal clone. Color comes from the
  collaborator "ink" palette above, hashed per user; teal is excluded
  from that hash and reserved for the AI.
  Sources consulted: [Building Figma Multiplayer Cursors](https://mskelton.dev/blog/building-figma-multiplayer-cursors),
  [y-codemirror.next README](https://github.com/yjs/y-codemirror.next/blob/main/README.md).

## Anti-slop / quality tooling (binding for implementation)

- **`impeccable`** — anti-AI-slop hook; fires automatically on file
  writes/edits. Findings get fixed or explicitly justified in the moment
  they're raised, never silently suppressed. (Already caught and fixed
  two real issues while building this spec's own preview: an overused-font
  finding and a side-tab-border AI-slop tell.)
- **`ui-ux-pro-max`** (owner-installed), **`minimalist-ui`**,
  **`high-end-visual-design`**, **`design-taste-frontend`** — design-taste
  skills to lean on during implementation. `minimalist-ui`'s own
  description ("clean editorial, warm monochrome, typographic contrast, no
  gradients/heavy shadows") is the closest existing match to this system.
- **`frontend-design`** (Anthropic official, github.com/anthropics/skills)
  — production-grade, non-generic frontend code generation.
- **`gsap-skills`** (GreenSock official) — correct GSAP implementation
  (timelines, ScrollTrigger, performance, React integration).
- Higgsfield skills are available for visual reference/inspiration only —
  not used to generate production assets.

## Preview

A verified HTML preview (fonts/colors/spacing/both themes, mockups of the
Editor/Auth/Settings pages) was built and screenshotted during design —
not committed to the repo (it's a throwaway artifact, not a build output).

## Decisions log

| Date | Decision | Rationale |
|---|---|---|
| 2026-07-19 | Light-first "paper & ink" system, dark as secondary "night mode" | Direct expression of "plain files, yours forever" — reverses the category's dark-first convention on purpose. |
| 2026-07-19 | Dual-accent authorship color system (human vermillion / AI teal) | Makes permission-scoped AI involvement legible everywhere, not buried in a settings page — the product's actual differentiator, expressed visually. |
| 2026-07-19 | Fraunces → Petrona, Plus Jakarta Sans → Hanken Grotesk | `impeccable` anti-slop audit: both original picks are now overused AI-generated-UI defaults. Swapped before shipping, same character retained. |
| 2026-07-19 | Ink-fade decay (graph) + collaborator ink palette (cursors) added | Owner's explicit ask to think outside the box the way Yildizim does — both translate an existing Yildizim mechanic into this edition's own material rather than a watered-down copy. |
