# Plan — Sub-project 1: Auth & Vault/Sharing (backend)

Spec: `docs/superpowers/specs/2026-07-09-auth-vault-sharing-design.md`
(including its security-hardening section). This plan lists tasks and
implementation-time decisions only — it does not restate the spec.

## Implementation-time decisions

- **DB layer**: Drizzle ORM + `postgres` driver. Schema in
  `server/src/db/schema.ts`; SQL migrations generated by drizzle-kit into
  `server/drizzle/`, run automatically at boot and in test setup.
- **Passwords**: argon2id via `@node-rs/argon2` (prebuilt binding).
- **Sessions**: 256-bit random token in an `HttpOnly`/`Secure`/
  `SameSite=Lax` cookie; only its SHA-256 hash stored (`sessions` table,
  30-day expiry). Logout/password-change/deactivation delete rows.
- **Teams**: no `owner_id` column — ownership is a `team_memberships`
  row with role `owner` (matches the spec's TeamMembership model).
- **Access resolution**: one function `resolveAccess(userId, vaultId)` →
  `'owner' | 'edit' | 'read' | null`, single place, three indexed
  lookups (own / direct share / team share), highest wins. Requires
  user status `active`. Every later sub-project calls this.
- **Bootstrap**: `instance_state` single-row table. First boot generates
  a setup token (or takes `SETUP_TOKEN` env), prints it to the log,
  stores its hash. `POST /api/setup` claims the initial active admin;
  signup is 404 until setup completes.
- **Email**: `mailer` interface — SMTP (nodemailer) in prod via env,
  recording stub in dev/test. Verification + reset use 6-digit codes /
  tokens stored hashed in `email_tokens`, single-use, 30-min expiry.
- **Throttling**: `@fastify/rate-limit` per-IP on login/signup/reset;
  per-account lockout via failed-attempt counter.
  <!-- ponytail: per-account counter is in-memory per-process; move to DB if multi-process -->
- **Notifications**: `notifications` table + `notify()` helper (in-app
  row + best-effort email) built now; list/mark-read endpoints come with
  the notifications sub-phase. Triggers wired where events happen.
- **MCP connections**: CRUD + token issue (shown once, stored hashed) +
  revoke + list with last-used. Bearer-token resolution helper for
  sub-project 6.

## Tasks (TDD; commit per green cycle)

1. Config module + DB client + schema + migrations + test harness
   (fresh schema per test run against local Postgres).
2. Passwords, sessions, `requireAuth` hook, security-event log helper.
3. Bootstrap `/api/setup`; signup → verify-email (code) → admin approve
   → login/logout/me; login throttling; password reset flow.
4. Vaults CRUD + `mergeable`; teams + memberships; shares (owner-only);
   `resolveAccess` with full test matrix; graph preferences (live-access
   guarded); ownership transfer; deactivation cascades + session kill.
5. MCP connection CRUD + token auth resolution (live permission check).
6. Notification triggers (share, team membership incl. owners-of-shared-
   vaults, approval/status change).

Deliverable: all auth/vault/team/share/MCP-connection endpoints tested
green; promoted to prod.
